#!/bin/bash

jupyter labextension install @jupyterlab/git
jupyter serverextension enable --py jupyterlab_git
git config --global user.name "Jean Lin"
git config --global user.email minclin@indiana.edu
